name: E2E Tests
on: 
    workflow_dispatch:
    workflow_call:
      secrets: 
        access-token:
          required: true
jobs:
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4.2.2
              with:
                repository: Ma4kaigrisho/github-actions-course-example-e2e
                ref: master
                token: ${{secrets.access || secrets.GITHUB_TOKEN}}
            - name: Setup Node
              uses: actions/setup-node@v4.2.0
              with:
                node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Run E2E tests
              run: npm run test:e2e
            